import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toaster from "@/app/toaster";
import { Github } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster />
        <div className="fixed top-4 right-4">
          <a
            className="rounded-full p-2"
            href="https://github.com/inaridiy/world_corner_note"
          >
            <Github size={32} />
          </a>
        </div>
      </body>
    </html>
  );
}
